sudo: required

services:
    - docker

before_install:
    - docker build -t islam93ahmed/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true islam93ahmed/docker-react  npm run test